apiVersion: v1
kind: Pod
metadata:
  name: dynamic-pod
  namespace: dynamic-storage-lab
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: dynamic-storage
          mountPath: /data
  volumes:
    - name: dynamic-storage
      persistentVolumeClaim:
        claimName: dynamic-pvc
