apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  namespace: storage-lab
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: storage
          mountPath: /data
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: storage-lab-pvc
