apiVersion: v1
kind: Pod
metadata:
  name: nginx-storage
spec:
  containers:
    - name: nginx
      image: nginx:latest

      volumeMounts:
        - name: website-storage
          mountPath: /usr/share/nginx/html

  volumes:
    - name: website-storage
      persistentVolumeClaim:
        claimName: storage-lab-pvc
