
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
  namespace: service-lab
spec:
  type: LoadBalancer
  selector:
    app: nodeport-nginx
  ports:
    - port: 80
      targetPort: 80
