
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  namespace: service-lab
spec:
  type: NodePort
  selector:
    app: nodeport-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
