
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: service-lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-demo
  template:
    metadata:
      labels:
        app: web-demo
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

