apiVersion: v1
kind: Pod

metadata:
  name: storage-pod

spec:
  containers:
    - name: nginx
      image: nginx:latest

      volumeMounts:
        - name: storage
          mountPath: /data

  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: my-pvc
