apiVersion: v1
kind: Pod
metadata:
  name: expansion-pod
  namespace: pvc-expansion-lab
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: storage
          mountPath: /data
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: expansion-pvc
