apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expansion-pvc
  namespace: pvc-expansion-lab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pvc-expansion
  resources:
    requests:
      storage: 1Gi
