apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab40-mysql-pvc
  namespace: pv-pvc-final
spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: lab40-mysql

  resources:
    requests:
      storage: 3Gi
