apiVersion: v1
kind: Pod
metadata:
  name: lab39-pod
  namespace: troubleshooting-lab
spec:
  nodeSelector:
    kubernetes.io/hostname: nonexistent-node

  containers:
    - name: nginx
      image: nginx

      volumeMounts:
        - name: storage
          mountPath: /data

  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: lab39-pvc
