apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab36-pvc
  namespace: troubleshooting-lab
spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: manual

  resources:
    requests:
      storage: 10Gi


