apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab36-pv
spec:
  capacity:
    storage: 5Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  storageClassName: manual

  hostPath:
    path: /data/lab36
    type: DirectoryOrCreate
