apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab39-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: lab39-storage
  hostPath:
    path: /data/lab39
    type: DirectoryOrCreate
