apiVersion: v1
kind: Pod
metadata:
  name: lab36-pod
  namespace: troubleshooting-lab

spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: storage
          mountPath: /data

  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: lab36-pvc
